image: node:20.8.0

code_quality:
    before_script:
        - npm ci
    script:
        - npm run eslint
        - npm run stylelint
        - npm run prettier
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

pages:
    stage: deploy
    before_script:
        - echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
        - npm ci
    script:
        - npm run build
        - rm -rf public
        - cp -r dist public
        - rm .env
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
